### ISSUE TITLE
🚀 feat(openfga): OpenFGA Permission policy extension

### ISSUE THREAD

**Issue by evghen1** [web-seven/backstage-plugins#58]
### Plugin Name

backstage-plugin-openfga

### 🔖 Feature description

This feature will check permission policies of OpenFGA against permission requests from Backstage.

### 🎤 Context

Backstage hasn't integrated permission policy checker, where possible to call external RBAC system and check if resource request is allowed. For that possible to create permission policy extension where call OpenFGA and return policy assert.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/web-seven/backstage-plugins/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aaguiarz** [comment]
@evghen1 pretty cool! I subscribed to see the progress :)

**Comment by evghen1** [comment]
> @evghen1 pretty cool! I subscribed to see the progress :) 
> 
> 

We plan just basic features soon, but any feedback will be appreciated. Stay tuned :)

**Comment by aaguiarz** [comment]
@evghen1 let me know if you want to demo it on our next [OpenFGA community meeting](https://github.com/openfga/community/blob/main/community-meetings.md) :)

**Comment by evghen1** [comment]
@aaguiarz Is not ready for demo yet, we are just finished with fulfilling of authz model from backstage permissions and tuples editor for user groups, but is not tested enough yet.
